#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}.{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: C:\projects\smoksmog-windows

# scripts that run after cloning repository
install:
- ps: >-
    Import-PfxCertificate -FilePath "C:\projects\smoksmog-windows\App\SmokSmog.App.UWP\SmokSmog.App.UWP_TemporaryKey.pfx" -CertStoreLocation cert:\CurrentUser\My > $null 2> $null

    Import-PfxCertificate -FilePath "C:\projects\smoksmog-windows\App\SmokSmog.App.win81\SmokSmog.App.win81_TemporaryKey.pfx" -CertStoreLocation cert:\CurrentUser\My > $null 2> $null

    Import-PfxCertificate -FilePath "C:\projects\smoksmog-windows\Core\SmokSmog.Core.WinRT.Tests\SmokSmog.Core.WinRT.Tests_TemporaryKey.pfx" -CertStoreLocation cert:\CurrentUser\My > $null 2> $null
    
    # Install MultilingualAppToolkit.msi

    $msiPath = "$($env:USERPROFILE)\MultilingualAppToolkit.msi"

    (New-Object Net.WebClient).DownloadFile('https://visualstudiogallery.msdn.microsoft.com/6dab9154-a7e1-46e4-bbfa-18b5e81df520/file/143697/18/MultilingualAppToolkit.msi', $msiPath)

    cmd /c start /wait msiexec /i $msiPath /q


#---------------------------------#
#       build configuration       #
#---------------------------------#
configuration: AppVeyor

build:
  project: SmokSmog.vs2015.sln
  parallel: true
  verbosity: minimal

before_build:
- ps: >-
    C:\projects\smoksmog-windows\.nuget\NuGet.exe update -self
    C:\projects\smoksmog-windows\.nuget\NuGet.exe restore C:\projects\smoksmog-windows\SmokSmog.vs2015.sln > $null 2> $null

#---------------------------------#
#       tests configuration       #
#---------------------------------#

after_test:
- ps: C:\projects\smoksmog-windows\codecov.ps1

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off